### PR TITLE
Use more common term for glossary in lithuanian

### PR DESCRIPTION
**Pull request by yjhn**

### CODE REVIEW

**Comment by ivankokan** [comment]
You should also consider changing in `lithuanian` and `polyglossia` packages.

**Comment by yjhn** [comment]
Polyglossia [already defines](https://github.com/reutenauer/polyglossia/blob/master/tex/gloss-lithuanian.ldf#L39) `glossary` as `Terminų žodynas`. `lithuanian` package has no (public) repository, it seems.

**Comment by ivankokan** [comment]
Reach the author directly.

**Comment by yjhn** [comment]
Contacted the author and they said that this will be done with the next `lithuanian` package update.

**Pull request merged**
